//
//  BackgroundSpriteView.swift
//  chewy
//
//  Animated background via SpriteKit.
//  Expects background.spriteatlas in Assets.xcassets with frames named
//  "background_000", "background_001", … (generated by video_to_spritesheet.py)
//
//  While the atlas is not yet available the view shows a solid fallback color.
//

import SwiftUI
import SpriteKit

// MARK: - SwiftUI wrapper

struct BackgroundSpriteView: View {
    var body: some View {
        GeometryReader { geo in
            SpriteView(scene: makeScene(size: geo.size), options: [.allowsTransparency])
                .ignoresSafeArea()
        }
        .ignoresSafeArea()
    }

    private func makeScene(size: CGSize) -> BackgroundScene {
        let scene = BackgroundScene(size: size)
        scene.backgroundColor = .clear
        scene.scaleMode = .aspectFill
        return scene
    }
}

// MARK: - SKScene

final class BackgroundScene: SKScene {

    private static let framePrefix = "klbackground_"
    private static let fps: Double = 24

    override func didMove(to view: SKView) {
        backgroundColor = .clear

        let atlas = SKTextureAtlas(named: "background")

        // Atlas not ready yet — nothing to animate
        guard atlas.textureNames.count > 0 else { return }

        let frameNames = atlas.textureNames
            .filter { $0.hasPrefix(Self.framePrefix) }
            .sorted()

        guard !frameNames.isEmpty else { return }

        let textures = frameNames.map { name -> SKTexture in
            let tex = atlas.textureNamed(name)
            tex.filteringMode = .linear
            return tex
        }

        let node = SKSpriteNode(texture: textures.first)
        node.size = size
        node.position = CGPoint(x: size.width / 2, y: size.height / 2)
        addChild(node)

        let anim = SKAction.animate(with: textures, timePerFrame: 1.0 / Self.fps)
        node.run(SKAction.repeatForever(anim))
    }
}
